name: Wiki Storage Telegram Bot

on:
  workflow_dispatch:
    
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install requirements
      run: pip install -r .github/workflows/wiki_storage_telegram_bot/requirements.txt
    - name: Run WikiStorageBot
      run: python3 .github/workflows/wiki_storage_telegram_bot/wiki_storage_telegram_bot.py
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_SECRET_TOKEN: ${{ secrets.TELEGRAM_SECRET_TOKEN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_AUTH: ${{ secrets.FIREBASE_AUTH }}  
    - name: Update repo
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Alejandroid17
        author_email: alejandrofernandezm94@gmail.com
        message: '[GitHub Actions] - New entries, more fun!'
        add: '*'
